### ISSUE TITLE
Download data not working

### ISSUE THREAD

**Issue by Sean-Morrison** [sdss/zora#17]
The Download data option has "undefined" in the paths provided by all of the options. I see this when testing with https://data.sdss5.org/zora/target/17912762

**Comment by havok2063** [comment]
This is working in my dev environment.  I fixed the proxy issue so it's not that.  This may be due to some differences in the timings of when/how UI components get rendered in production mode versus a development mode.  I'll have to investigate further.

**Comment by havok2063** [comment]
The issue was in the way we were mounting the SAS to the production valis.  We were not mounting into a `/sas/` sub-directory, and the DataDownload.vue component explicitly uses that key for path manipulation.  This should be fixed now and re-deployed to production.
