### ISSUE TITLE
Program/Carton Constraints not working

### ISSUE THREAD

**Issue by imedan** [sdss/zora#18]
It seems like when doing a full search, specifying a program and/or carton with a cone search does not change the result. It seems like even when this is added, it still returns all targets within the cone search, not just those limited to a specific carton/program. I imagine this is a `zora` issue? Let me know if this belongs under `valis` though.

**Comment by havok2063** [comment]
This is a known valis issue with how the query is constructed.  I haven't had time to fix it or to think about the best approach.  You can see the issue here, https://github.com/sdss/valis/blob/576d2092be55c5043e62d4e15bf8bd209a1e6e1f/python/valis/routes/query.py#L81.

**Comment by havok2063** [comment]
@imedan Did you mean to close this issue or are you migrating it to valis?

**Comment by imedan** [comment]
Yes, I was going to move it to valis. It can be found here now: https://github.com/sdss/valis/issues/20
